---
name: Lint, test, build, and publish
on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish beta version
    if: contains(github.ref, 'beta')
    runs-on: ubuntu-latest
    steps:
    - uses: google-github-actions/auth@v0.4.3
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}

    - name: Get common secrets
      id: secrets
      uses: google-github-actions/get-secretmanager-secrets@v0.3.2
      with:
        secrets: |-
          slack:um-cloud-production/slack
          github:um-cloud-production/github

    - uses: actions/checkout@v2

    - name: NPM cache
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}

    - uses: actions/setup-node@v2
      with:
        node-version: 16

    - run: npm ci
      env:
        GITHUB_TOKEN: ${{ fromJson(steps.secrets.outputs.github).token }} # Needed because we install private packages from npm.pkg.github.com

    - run: npm publish --tag beta
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Stardust - Deploy
        fields: repo,commit,message,author
      env:
        SLACK_WEBHOOK_URL: ${{ fromJson(steps.secrets.outputs.slack).webhook }}
        SLACK_USERNAME: Stardust
      if: failure()
