name: Lint, test, build, and publish
on:
  release:
    types:
      - published

env:
  # Vault settings
  VAULT_ADDR: https://vault-eyzrjbz27a-ew.a.run.app/
  # To get the role id, change to the terraform production environment directory, and run:
  # terraform state pull | jq '.resources[] | select(.type=="vault_approle_auth_backend_role" and .name=="github").instances[].attributes.role_id'
  VAULT_ROLE_ID: 572856f8-3509-d6f8-7369-11468e595488

jobs:
  publish:
    name: Publish regular version
    if: "!contains(github.ref, 'beta')"
    runs-on: ubuntu-latest
    steps:
    - name: Get common secrets
      uses: hashicorp/vault-action@v2.3.1
      id: secrets
      with:
        url: ${{ env.VAULT_ADDR }}
        method: approle
        roleId: ${{ env.VAULT_ROLE_ID }}
        secretId: ${{ secrets.VAULT_SECRET_ID }}
        secrets: |
          secret/data/systems/common/npm token | NPM_TOKEN;
          secret/data/systems/common/slack webhook | SLACK_WEBHOOK_URL
    - uses: actions/checkout@v2
    - name: Npm cache
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: npm-${{ hashFiles('**/package-lock.json') }}
    - uses: actions/setup-node@v1
      with:
        node-version: 12.13.1
    - run: npm ci
    - run: npm publish
    - uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        author_name: Stardust - Deploy
        fields: repo,commit,message,author
      env:
        SLACK_USERNAME: Stardust
      if: failure()
